name = "moonlander-scores"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "SCORES"
# Replace with your KV namespace ID after running:
#   wrangler kv:namespace create SCORES
id = "ba1dc56821984c3f8be2a6ebc0ee985b"
